CPP=LED.cpp roue.cpp memoire_24.cpp transmissionUART.cpp timer_materiel.cpp timer_logiciel.cpp boutonEnfonce.cpp can.cpp son.cpp capteur_distance.cpp customprocs.cpp lcm_so1602dtr_m.cpp lcm_so1602dtr_m_fw.cpp senseur_magnet.cpp
PROJECTNAME=librobot
INC=-I ../includes 
LIBS=
SL=avr-ar crs
TRG=$(PROJECTNAME).a
TRG_cmd= $(SL) $(TRG) $(OBJDEPS) 
C=-c
INK=

-include ../Makefile_Common.txt
