
CPP=Entraineur.cpp
PROJECTNAME=mainrobot
INC=
LIBS=-L ../lib_dir -lrobot
TRG=$(PROJECTNAME).out
TRG_cmd=$(CC) $(LDFLAGS) -o $(TRG) $(OBJDEPS) \
	-lm $(LIBS)
C=
INK=$(INC)

-include ../Makefile_Common.txt
